name: code_generators
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Jermaine Oppong

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  build: ^1.1.6
  path: ^1.6.0

dev_dependencies:
  build_config: ^0.4.1+1
  build_runner: ^1.6.6
  pedantic: ^1.7.0
  test: ^1.5.0
